
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `u_sponsor`, `parentid`, `position`, `matrix_pool`, `matrix_position`, `username`, `eth_address`, `user_type`, `title`, `mobile`, `tx_password`, `set_user_password_status`, `is_fan`, `address`, `address2`, `father_name`, `city`, `gender`, `dob`, `email_code`, `is_email_verify`, `post_code`, `country`, `country_code`, `marital_status`, `pan_no`, `direct`, `img`, `state`, `admin_register_status`, `active_id`, `active_status`, `trade_status`, `rank_id`, `retopup_status`, `fast_achiever_rank`, `token_status`, `retopup_date`, `installment_date`, `block_status`, `pass_status`, `tx_pass_status`, `profile_edited`, `active_date`, `sip_status`, `sip_date`, `my_package`, `my_rank`, `salary_rank`, `income_per`, `growth_rank`, `rank_bonus`, `pkg_type`, `income_status`, `booster_status`, `booster1_status`, `booster2_status`, `booster3_status`, `booster1_date`, `booster2_date`, `booster3_date`, `auto_register`, `notifications`, `updated_on`, `added_on`, `nominee_name`, `nominee_relation`, `nominee_dob`, `instagram_link`, `facebook_link`, `twitter_link`, `telegram_link`, `snap_chat`, `roi_income`, `booster_income`, `level_roi_income`) VALUES (NULL, 'phoenix', 'phoenix@gmail.com', NULL, '$2y$10$4UDXwB1Gk18L2kXuUVpF.u7XX3mEDEooKyCG/so92FyPLO920QpEW', NULL, '2024-12-21 09:19:40', '2024-12-12 11:11:11', '2', NULL, NULL, NULL, NULL, 'TE121212', NULL, NULL, NULL, '9876543214', NULL, '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, '0', '1', '1', '0', '1', '0', NULL, '0', NULL, NULL, '0', '0', '0', '0', '2024-12-21 09:21:29', '0', NULL, '0', NULL, NULL, '0', NULL, NULL, '0', '1', '0', '0', '0', '0', NULL, NULL, NULL, NULL, '0', '2024-12-12 11:11:11', '2024-12-12 11:11:11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '1', '1');

INSERT INTO `advanced_info` (`id`, `title`, `name`, `label`, `type`, `options`, `image`, `value`, `status`, `admin_status`, `created_at`, `updated_at`) VALUES
(1, 'Registration', 'Max Mobile Per Users', 'mobile_users', 'text', '', '', '1000', 1, 1, '2024-12-12 11:11:11', NULL),
(2, 'Registration', 'Max Email Per Users', 'email_users', 'text', '', '', '1000', 1, 1, '2024-12-12 11:11:11', NULL),
(3, 'Registration', 'Registration Type', 'reg_type', 'array', '{\"single_leg\":\"Single Leg\",\"binary\":\"Binary\",\"ecommerce\":\"Product Base\",\"generation\":\"Generation\",\"universal\":\"Matrix\",\"repurchase\":\"Repurchase\"}', '', 'generation', 1, 0, '2024-12-12 11:11:11', NULL),
(4, 'Registration', 'Country Code', 'country_code', 'option', 'yes,no', '', 'yes', 1, 0, '2024-12-12 11:11:11', NULL),
(5, 'Registration', 'UserName Generation Method', 'user_gen_method', 'option', 'automatic,manual', '', 'automatic', 1, 0, '2024-12-12 11:11:11', NULL),
(6, 'Registration', 'UserName Generation Function', 'user_gen_fun', 'array', '{\"alnum\":\"Alpha-Numeric\",\"numeric\":\"Numeric Only\",\"alpha\":\"Alpha Only\"}', '', 'numeric', 1, 0, '2024-12-12 11:11:11', NULL),
(7, 'Registration', 'UserName Generation Digit ', 'user_gen_digit', 'text', '', '', '6', 1, 0, '2024-12-12 11:11:11', NULL),
(8, 'Registration', 'UserName Generation Prefix', 'user_gen_prefix', 'text', '', '', 'TE', 1, 1, '2024-12-12 11:11:11', NULL),
(9, 'Registration', 'Password Generation Type', 'pass_gen_type', 'option', 'automatic,manual', '', 'manual', 1, 0, '2024-12-12 11:11:11', NULL),
(10, 'Registration', 'Password Generation Function', 'pass_gen_fun', 'array', '{\"alnum\":\"Alpha-Numeric\",\"numeric\":\"Numeric Only\",\"alpha\":\"Alpha Only\"}', '', 'alnum', 1, 0, '2024-12-12 11:11:11', NULL),
(11, 'Registration', 'Password Generation Alphabets Digits', 'pass_gen_digit', 'text', '', '', '6', 1, 0, '2024-12-12 11:11:11', NULL),
(12, 'Registration', 'Is sponsor required', 'is_sponsor_required', 'option', 'yes,no', '', 'yes', 1, 0, '2024-12-12 11:11:11', NULL),
(13, 'Withdrawal', 'Withdrawal Limit', 'min_withdrawal_limit', 'text', 'per', '', '50', 1, 0, '2024-12-12 11:11:11', NULL),
(14, 'Withdrawal', 'Withdrawal Status', 'withdrawal_status', 'option', 'off,on', '', 'off', 1, 0, '2024-12-12 11:11:11', NULL);

INSERT INTO `pin_details` (`id`, `pin_type`, `pin_rate`, `max_pin_rate`, `business_volumn`, `pin_value`, `pkg_type`, `pool_type`, `pool_id`, `package_name`, `status`, `roi`, `refferal`, `booster_roi`, `days`, `jago_trade`, `package_type`, `created_at`, `updated_at`) VALUES (NULL, 'Package1', '100', '100000', '0', '1', '1', NULL, '0', NULL, '1', '0.5', '0', '0', '0', '1', NULL, NULL, NULL);